// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { ConfirmedTransaction } from "./ConfirmedTransaction";
import { Reward } from "./Reward";
import { UnixTimestamp } from "./UnixTimestamp";
import { BlockHeight } from "./BlockHeight";

export class Block {
  static encode(message: Block, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.previousBlockhash);

    writer.uint32(18);
    writer.string(message.blockhash);

    writer.uint32(24);
    writer.uint64(message.parentSlot);

    const transactions = message.transactions;
    for (let i: i32 = 0; i < transactions.length; ++i) {
      writer.uint32(34);
      writer.fork();
      ConfirmedTransaction.encode(transactions[i], writer);
      writer.ldelim();
    }

    const rewards = message.rewards;
    for (let i: i32 = 0; i < rewards.length; ++i) {
      writer.uint32(42);
      writer.fork();
      Reward.encode(rewards[i], writer);
      writer.ldelim();
    }

    const blockTime = message.blockTime;
    if (blockTime !== null) {
      writer.uint32(50);
      writer.fork();
      UnixTimestamp.encode(blockTime, writer);
      writer.ldelim();
    }

    const blockHeight = message.blockHeight;
    if (blockHeight !== null) {
      writer.uint32(58);
      writer.fork();
      BlockHeight.encode(blockHeight, writer);
      writer.ldelim();
    }

    writer.uint32(160);
    writer.uint64(message.slot);
  }

  static decode(reader: Reader, length: i32): Block {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Block();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.previousBlockhash = reader.string();
          break;

        case 2:
          message.blockhash = reader.string();
          break;

        case 3:
          message.parentSlot = reader.uint64();
          break;

        case 4:
          message.transactions.push(
            ConfirmedTransaction.decode(reader, reader.uint32())
          );
          break;

        case 5:
          message.rewards.push(Reward.decode(reader, reader.uint32()));
          break;

        case 6:
          message.blockTime = UnixTimestamp.decode(reader, reader.uint32());
          break;

        case 7:
          message.blockHeight = BlockHeight.decode(reader, reader.uint32());
          break;

        case 20:
          message.slot = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  previousBlockhash: string;
  blockhash: string;
  parentSlot: u64;
  transactions: Array<ConfirmedTransaction>;
  rewards: Array<Reward>;
  blockTime: UnixTimestamp | null;
  blockHeight: BlockHeight | null;
  slot: u64;

  constructor(
    previousBlockhash: string = "",
    blockhash: string = "",
    parentSlot: u64 = 0,
    transactions: Array<ConfirmedTransaction> = [],
    rewards: Array<Reward> = [],
    blockTime: UnixTimestamp | null = null,
    blockHeight: BlockHeight | null = null,
    slot: u64 = 0
  ) {
    this.previousBlockhash = previousBlockhash;
    this.blockhash = blockhash;
    this.parentSlot = parentSlot;
    this.transactions = transactions;
    this.rewards = rewards;
    this.blockTime = blockTime;
    this.blockHeight = blockHeight;
    this.slot = slot;
  }
}
