// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class BlockHeight {
  static encode(message: BlockHeight, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.blockHeight);
  }

  static decode(reader: Reader, length: i32): BlockHeight {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new BlockHeight();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.blockHeight = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  blockHeight: u64;

  constructor(blockHeight: u64 = 0) {
    this.blockHeight = blockHeight;
  }
}
