// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class UnixTimestamp {
  static encode(message: UnixTimestamp, writer: Writer): void {
    writer.uint32(8);
    writer.int64(message.timestamp);
  }

  static decode(reader: Reader, length: i32): UnixTimestamp {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new UnixTimestamp();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.timestamp = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  timestamp: i64;

  constructor(timestamp: i64 = 0) {
    this.timestamp = timestamp;
  }
}
